/* ==========================================================================
   THRAGG — Report Builder
   Collects and normalizes report data into a canonical Report Model.
   ========================================================================== */

const THRAGG_ReportBuilder = {
  buildCanonicalModel() {
    const data = window.THRAGG_DATA || {};
    const caseObj = (typeof THRAGG_CaseManager !== 'undefined') ? THRAGG_CaseManager.getActiveCase() : null;
    const replayEvents = (typeof THRAGG_ReplayEngine !== 'undefined') ? THRAGG_ReplayEngine.events : [];
    
    const snapshot = data.framework_snapshot || {};
    const assessment = data.executive_assessment || {};

    // 1. Metadata
    const metadata = {
      report_id: 'RPT-' + Math.random().toString(36).substr(2, 9).toUpperCase(),
      generated_at: new Date().toISOString(),
      case_id: caseObj ? caseObj.id : 'N/A',
      case_title: caseObj ? caseObj.title : 'Incident Assessment',
      case_status: caseObj ? caseObj.status : 'N/A',
      severity: caseObj ? caseObj.severity : (snapshot.highest_risk_level || 'UNKNOWN'),
      analyst: caseObj ? caseObj.analyst : 'Automated System',
      tags: caseObj ? caseObj.tags : []
    };

    // 2. Executive Summary
    const executive_summary = {
      summary: assessment.executive_summary || 'No executive summary generated by intelligence engine.',
      primary_risks: assessment.primary_risks || [],
      posture_score: snapshot.security_posture_score || 0
    };

    // 3. Investigation Context (Notes & Bookmarks)
    const investigation = {
      notes: caseObj ? caseObj.notes : [],
      bookmarks: caseObj ? caseObj.bookmarks : []
    };

    // 4. Replay Summary
    const replay = {
      total_steps: replayEvents.length,
      start_time: replayEvents.length > 0 ? replayEvents[0].timestamp : null,
      end_time: replayEvents.length > 0 ? replayEvents[replayEvents.length - 1].timestamp : null,
      steps: replayEvents.map(ev => ({
        stage: ev.title,
        timestamp: ev.timestamp,
        source: ev.source_id,
        target: ev.target_id,
        mitre: ev.mitre,
        description: ev.description
      }))
    };

    // 5. Findings
    const findings = (assessment.observations || []).map(obs => ({
      id: obs.id || obs.category,
      category: obs.category,
      severity: obs.severity,
      summary: obs.summary,
      entities: obs.entities || [],
      mitre: obs.mitre || []
    }));

    // 6. Relationships & Entities
    const relationships = (data.relationships || []).map(r => ({
      source: r.source_entity_id || r.source,
      target: r.target_entity_id || r.target,
      type: r.relationship_type || r.type,
      description: r.description
    }));

    // 7. Correlations
    const correlations = (data.correlations || []).map(c => ({
      id: c.id,
      title: c.title,
      summary: c.summary,
      severity: c.severity,
      entities: c.entities || [],
      mitre: c.mitre || []
    }));

    // 8. MITRE
    const mitre_techniques = {};
    correlations.forEach(c => (c.mitre || []).forEach(m => mitre_techniques[m] = (mitre_techniques[m]||0)+1));
    (data.attack_chains || []).forEach(ac => (ac.mitre_techniques || []).forEach(m => mitre_techniques[m] = (mitre_techniques[m]||0)+1));
    
    const mitre = Object.keys(mitre_techniques).map(m => ({ technique: m, count: mitre_techniques[m] }));

    // 9. Evidence
    const evidence = [];
    (data.attack_chains || []).forEach(chain => {
      (chain.steps || []).forEach(step => {
        (step.evidence || []).forEach(ev => {
           evidence.push({ source: ev.source, data: ev.data, reference: chain.id });
        });
      });
    });

    // 10. Recommendations
    const recommendations = (data.recommendations || []).map(r => ({
      id: r.id,
      title: r.title,
      priority: r.priority,
      description: r.description,
      effort: r.effort
    }));

    // 11. Timeline
    const timeline = caseObj ? caseObj.timeline : [];

    // Return Canonical Model
    return {
      metadata,
      executive_summary,
      investigation,
      replay,
      findings,
      relationships,
      correlations,
      mitre,
      evidence,
      recommendations,
      timeline,
      appendices: []
    };
  }
};
